apiVersion: apps.k8smgmt.io/v3
kind: WorkloadTemplate
metadata:
  name: workload-tmpl-helm-repository
  project: vivek
spec:
  artifact:
    artifact:
      chartPath:
        name: charts/sample-chart/Chart.yaml
      repository: workload-template-repository
      revision: main
      valuesPaths:
      - {}
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
