apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: ballot-deployment.yaml
      repository: my-k8s-repository
      revision: main
      valuesPaths:
      - {}
      valuesRef:
        repository: my-k8s-repository
        revision: main
        valuesPaths:
        - name: ballot-deployment.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: mnop22
  placement:
    selector: rafay.dev/clusterName=remote-minikube-cluster-august28
  version: test-v1-202509180857490000
