apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test123
  project: defaultproject
spec:
  artifact:
    artifact:
      chartName: mychart
      chartVersion: 0.1.3
      repository: default-bitnami
      valuesRef:
        repository: my-k8s-repository
        revision: main
        valuesPaths:
        - name: ballot-deployment.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: mnop22
