apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: tftestworkload6
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: chart/path/chart.tgz
      repository: my-k8s-repository
      revision: main
      valuesPaths:
      - name: value/path/values.yaml
      valuesRef:
        repository: my-k8s-repository
        revision: main
        valuesPaths:
        - name: value/path/values.yaml
    options:
      timeout: 0s
    type: Helm
  namespace: mnop22
  placement:
    selector: rafay.dev/clusterName=remote-minikube-cluster-august28
  version: v1
