apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: description for blueprint version v1
  name: aws-node-terminator-1
  project: defaultproject
spec:
  base:
    name: default
    version: 3.8.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    enableVM: true
    monitoring:
      gpuOperator: {}
      helmExporter:
        enabled: true
      kubeStateMetrics:
        enabled: true
      metricsServer:
        enabled: true
      nodeExporter:
        enabled: true
      prometheusAdapter:
        enabled: true
      resources: {}
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v7
  versionState: active
