apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custom-blueprint
  project: defaultproject
spec:
  base:
    name: default-upstream-kubeovn-chaining
    version: 3.8.0
  defaultAddons:
    disableAwsNodeTerminationHandler: true
    enableCsiSecretStore: true
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Managed
  type: custom
  version: v6
  versionState: active
