apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: new-helm-blueprint
  project: defaultproject
spec:
  base:
    name: default
    version: 3.8.0
  defaultAddons:
    disableAwsNodeTerminationHandler: true
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: with-aws-node-ter-handler-7
  versionState: active
