apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test-bp-without-aws-node-terminator
  project: defaultproject
spec:
  base:
    name: default
    version: 3.8.0
  defaultAddons:
    disableAwsNodeTerminationHandler: true
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
