apiVersion: apps.k8smgmt.io/v3
kind: WorkloadTemplate
metadata:
  name: mychart-test
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
