apiVersion: apps.k8smgmt.io/v3
kind: WorkloadTemplate
metadata:
  name: test1
  project: defaultproject
spec:
  artifact:
    artifact:
      chartName: mychart
      chartVersion: 0.1.3
      repository: default-bitnami
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
