apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: krishna-jul10
  project: vivek
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: vivek-local-minikube-july07
  resourceQuotas: {}
