apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: sample-namespace
  project: vivek
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: local-mk-dec16
  resourceQuotas:
    ephemeralStorageLimits: 10Mi
    ephemeralStorageRequests: 10Mi
    pods: "12"
