apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: vivek-test-3
  project: vivek
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: vivek-remote-minikube-cluster-sep24
